-- Sync event log foundation. Apply to a dedicated Supabase project before enabling cloud sync.
-- This is deliberately an event transport/log, not the authoritative browser-side business schema.

create table if not exists public.sync_events (
  server_seq bigint generated by default as identity primary key,
  event_id uuid not null unique,
  workspace_id text not null,
  business_id text not null,
  device_id text not null,
  actor_id text not null,
  entity_type text not null,
  entity_id text not null,
  operation text not null,
  payload jsonb not null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  auth_user_id uuid null default auth.uid()
);

create index if not exists sync_events_workspace_seq_idx on public.sync_events(workspace_id, server_seq);
create index if not exists sync_events_business_seq_idx on public.sync_events(business_id, server_seq);

alter table public.sync_events enable row level security;

-- Production note:
-- Do NOT deploy a permissive workspace policy. Create workspace_members first and replace
-- these deny-by-default policies with membership-checked INSERT/SELECT policies.
create policy "deny anonymous select" on public.sync_events for select using (false);
create policy "deny anonymous insert" on public.sync_events for insert with check (false);

comment on table public.sync_events is 'Immutable client event transport/log for local-first synchronization. Add authenticated workspace membership RLS before production.';
