import { expect, test, type Page } from '@playwright/test'

async function offlineReady(page: Page) {
  await page.evaluate(() => navigator.serviceWorker.ready.then(() => true))
  await page.reload()
  await page.waitForFunction(() => navigator.serviceWorker.controller !== null)
}

async function records(page: Page, table: string, name = 'RRWRS-Demo') {
  return page.evaluate(async ({ table, name }) => {
    const database = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(name); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error) })
    try { return await new Promise<Record<string, unknown>[]>((resolve, reject) => { const tx = database.transaction(table, 'readonly'), request = tx.objectStore(table).getAll(); request.onsuccess = () => resolve(request.result as Record<string, unknown>[]); request.onerror = () => reject(request.error) }) } finally { database.close() }
  }, { table, name })
}

test('offline standard workspace configures rice catalog, accounts and supplier then receives, sells and adjusts', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:4174')
  await expect(page.getByRole('heading', { name: 'No production workspace is configured' })).toBeVisible()
  await offlineReady(page); await context.setOffline(true)
  await page.getByLabel('Workspace name', { exact: true }).fill('Family stores')
  await page.getByLabel('Owner name', { exact: true }).fill('Store owner')
  await page.getByLabel('Business name', { exact: true }).fill('Local Bigasan')
  await page.getByRole('combobox', { name: 'Business type', exact: true }).selectOption('rice')
  await page.getByLabel('Location name', { exact: true }).fill('Rice store A')
  await page.getByRole('button', { name: 'Create local workspace' }).click()
  await expect(page.getByText('Trusted local workspace · no sign-in · cloud sync disabled')).toBeVisible()
  expect(await records(page, 'stockMovements', 'LocalFirstBusinessManager')).toHaveLength(0)
  await page.getByLabel('Business', { exact: true }).selectOption({ label: 'Local Bigasan' })
  await page.getByRole('button', { name: 'Manage', exact: true }).click()
  await page.getByLabel('Product name', { exact: true }).fill('Jasmine rice')
  await page.getByLabel('SKU', { exact: true }).fill('R-JAS')
  await page.getByLabel('Selling price per unit').fill('60')
  await page.getByRole('button', { name: 'Save product', exact: true }).click()
  await expect(page.getByText('Catalog item saved.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Accounts', exact: true }).click()
  await page.getByLabel('Account name', { exact: true }).fill('BPI operating account')
  await page.getByRole('combobox', { name: 'Account type', exact: true }).selectOption('bank')
  await page.getByRole('button', { name: 'Save account', exact: true }).click()
  await expect(page.getByText('Payment account saved locally.')).toBeVisible()
  await page.getByRole('button', { name: 'Suppliers', exact: true }).click()
  await page.getByLabel('Supplier name', { exact: true }).fill('Mill A')
  await page.getByRole('button', { name: 'Save supplier', exact: true }).click()
  await expect(page.getByText('Supplier saved locally.')).toBeVisible()
  await page.getByRole('button', { name: 'Ops', exact: true }).click()
  await page.getByLabel('Quantity received').fill('100')
  await page.getByLabel('Total supplier cost').fill('4800')
  await page.getByRole('combobox', { name: 'Supplier', exact: true }).selectOption({ label: 'Mill A' })
  await page.getByLabel('Supplier receipt/reference', { exact: true }).fill('INV-001')
  await page.getByRole('combobox', { name: 'Paid from', exact: true }).selectOption({ label: 'BPI operating account' })
  await page.getByRole('button', { name: 'Receive stock', exact: true }).last().evaluate((button: HTMLButtonElement) => { button.click(); button.click() })
  await expect(page.getByText('Stock received locally.', { exact: false })).toBeVisible()
  expect(await records(page, 'purchases', 'LocalFirstBusinessManager')).toHaveLength(1)
  expect(await records(page, 'purchaseLines', 'LocalFirstBusinessManager')).toHaveLength(1)
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await page.getByLabel('Quantity', { exact: false }).fill('5')
  await page.getByRole('combobox', { name: 'Paid via', exact: true }).selectOption({ label: 'BPI operating account' })
  await page.screenshot({ path: `test-results/m1-sale-${test.info().project.name}.png`, fullPage: true })
  await page.getByRole('button', { name: 'Finalize sale', exact: true }).evaluate((button: HTMLButtonElement) => { button.click(); button.click() })
  await expect(page.getByText('Sale saved locally.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Stock', exact: true }).click()
  await expect(page.locator('article').filter({ hasText: 'Jasmine rice' }).getByText('95 kg')).toBeVisible()
  await page.getByLabel('Quantity change').fill('-.3')
  await page.getByLabel('Adjustment reason', { exact: true }).fill('Witnessed discrepancy after recount')
  await page.getByRole('button', { name: 'Record permanent adjustment' }).click()
  await expect(page.getByText('Explained adjustment saved in the stock ledger.')).toBeVisible()
  await expect(page.locator('article').filter({ hasText: 'Jasmine rice' }).getByText('94.7 kg')).toBeVisible()
  await page.getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(page.getByRole('heading', { name: '₱300.00', exact: true })).toBeVisible()
  await expect(page.locator('.profit-chip').getByText('₱60.00', { exact: true })).toBeVisible()
  await expect(page.getByText('BPI operating account', { exact: true })).toBeVisible()
  await page.screenshot({ path: `test-results/m1-dashboard-${test.info().project.name}.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await expect(page.getByText('Mill A · INV-001', { exact: false })).toBeVisible()
  expect(await records(page, 'sales', 'LocalFirstBusinessManager')).toHaveLength(1)
  expect(await records(page, 'stockMovements', 'LocalFirstBusinessManager')).toHaveLength(3)
  await page.getByRole('button', { name: 'Manage', exact: true }).click()
  await page.getByRole('combobox', { name: 'Manage item', exact: true }).selectOption(String((await records(page, 'products', 'LocalFirstBusinessManager'))[0].id))
  await page.getByLabel('Selling price per unit').fill('65')
  await page.getByRole('button', { name: 'Save product', exact: true }).click()
  await expect(page.getByText('Catalog item saved.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await expect(page.locator('.sale-total strong')).toHaveText('₱300.00')
  await expect(page.getByRole('button', { name: 'Finalize sale' })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('heading', { name: '₱300.00', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('two tabs retry the same offline draft after a sale commits without duplicating it', async ({ page, context }) => {
  await page.goto('/'); await offlineReady(page); await context.setOffline(true)
  await page.getByLabel('Business', { exact: true }).selectOption({ label: 'Bigasan' })
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await page.getByLabel('Quantity').fill('5')
  await page.getByLabel('Paid via').selectOption({ label: 'GCash' })
  await expect.poll(async () => (await records(page, 'drafts')).some(d => (d.data as { quantity?: string }).quantity === '5')).toBe(true)
  const second = await context.newPage(); await second.goto('/')
  await second.getByLabel('Business', { exact: true }).selectOption({ label: 'Bigasan' })
  await second.getByRole('button', { name: 'Sale', exact: true }).click()
  await expect(second.getByLabel('Quantity')).toHaveValue('5')
  await page.getByRole('button', { name: 'Finalize sale', exact: true }).click()
  // Observe IndexedDB commit, then close immediately without relying on a success message.
  await expect.poll(async () => (await records(page, 'sales')).length).toBe(1)
  await page.close()
  await second.getByRole('button', { name: 'Finalize sale', exact: true }).click()
  await expect(second.getByText('Sale saved locally.', { exact: false })).toBeVisible()
  expect(await records(second, 'sales')).toHaveLength(1)
  expect(await records(second, 'saleLines')).toHaveLength(1)
  expect(await records(second, 'paymentEntries')).toHaveLength(1)
  expect((await records(second, 'stockMovements')).filter(m => m.reason === 'sale')).toHaveLength(1)
  expect(await records(second, 'outbox')).toHaveLength(1)
  await second.reload()
  await expect(second.getByRole('heading', { name: '₱275.00', exact: true })).toBeVisible()
})

test('offline cash and electronic payments, business expense and abono retain independent totals', async ({ page, context }) => {
  await page.goto('/'); await offlineReady(page); await context.setOffline(true)
  await page.getByLabel('Business', { exact: true }).selectOption({ label: 'Water Refilling Station' })
  await page.getByRole('button', { name: 'Ops', exact: true }).click()
  await page.getByRole('button', { name: 'Cash close', exact: true }).click()
  await page.getByLabel('Opening cash').fill('1000')
  await page.getByRole('button', { name: 'Open cash session' }).click()
  await expect(page.getByText('Expected now')).toBeVisible()
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await page.getByRole('combobox', { name: 'Item', exact: true }).selectOption({ label: 'Purified Water Refill — ₱30.00' })
  await page.getByLabel('Quantity').fill('3')
  await page.getByLabel('Paid via').selectOption({ label: 'GCash' })
  await page.getByRole('button', { name: 'Finalize sale' }).click()
  await expect(page.getByText('Sale saved locally.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'New sale', exact: true }).click()
  await page.getByRole('combobox', { name: 'Item', exact: true }).selectOption({ label: 'Purified Water Refill — ₱30.00' })
  await page.getByLabel('Quantity').fill('2')
  await page.getByRole('button', { name: 'Add to basket' }).click()
  await page.getByRole('combobox', { name: 'Item', exact: true }).selectOption({ label: 'New 5-Gallon Container — ₱190.00' })
  await page.getByRole('button', { name: 'Add to basket' }).click()
  await page.getByLabel('Paid via').selectOption({ label: 'Water Cash Drawer' })
  await page.getByRole('button', { name: 'Finalize sale' }).click()
  await expect(page.getByText('Sale saved locally.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Ops', exact: true }).click()
  await page.getByRole('button', { name: 'Expense', exact: true }).click()
  await page.getByLabel('Amount (₱)', { exact: true }).fill('100')
  await page.getByRole('combobox', { name: 'Payment account', exact: true }).selectOption({ label: 'Water Cash Drawer' })
  await page.getByRole('button', { name: 'Save expense' }).evaluate((button: HTMLButtonElement) => { button.click(); button.click() })
  await expect(page.getByText('Expense saved locally', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'New expense', exact: true }).click()
  await page.getByLabel('Amount (₱)', { exact: true }).fill('500')
  await page.getByRole('checkbox', { name: 'Owner paid personally (abono)' }).check()
  await page.getByRole('button', { name: 'Save expense' }).click()
  await expect(page.getByText('Expense saved as owner-funded abono;', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Cash close', exact: true }).click()
  await expect(page.locator('.cash-summary').getByText('₱1,150.00', { exact: true })).toBeVisible()
  await page.getByLabel('Actual cash counted').fill('1160')
  await page.getByLabel('Variance explanation').fill('Recounted; ten pesos over')
  await page.getByRole('button', { name: 'Close and reconcile' }).click()
  await expect(page.getByText('Variance ₱10.00 · Overage')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '₱340.00', exact: true })).toBeVisible()
  await expect(page.getByText('Variance ₱10.00 · Overage')).toBeVisible()
  expect(await records(page, 'expenses')).toHaveLength(2)
  expect(await records(page, 'ownerPayables')).toHaveLength(1)
  expect((await records(page, 'paymentEntries')).filter(p => p.kind === 'expense')).toHaveLength(1)
  await page.screenshot({ path: `test-results/m1-cash-${test.info().project.name}.png`, fullPage: true })
})
