import { expect, test, type Page } from '@playwright/test'

async function offlineReady(page: Page) {
  await page.evaluate(() => navigator.serviceWorker.ready.then(() => true))
  await page.reload()
  await page.waitForFunction(() => navigator.serviceWorker.controller !== null)
}

test('fresh standard build does not seed demo data and reloads offline', async ({ page, context }) => {
  await page.goto('http://127.0.0.1:4174')
  await expect(page.getByRole('heading', { name: 'No production workspace is configured' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Finalize sale' })).toHaveCount(0)
  await offlineReady(page)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'No production workspace is configured' })).toBeVisible()
})

test('built PWA persists an offline sale through tab close, reopen and offline reload', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByText('Practice workspace · sample data · cloud sync disabled')).toBeVisible()
  await offlineReady(page)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByText('Offline — local operations available')).toBeVisible()
  await expect(page.getByText('App shell ready for offline use on this device.')).toBeVisible()
  await page.getByLabel('Business', { exact: true }).selectOption({ label: 'Bigasan' })
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await page.getByRole('combobox', { name: 'Item', exact: true }).selectOption({ label: 'Sinandomeng — ₱55.00' })
  await page.getByLabel('Quantity').fill('5')
  await page.getByLabel('Paid via').selectOption({ label: 'Rice Cash Drawer' })
  await page.getByRole('button', { name: 'Finalize sale' }).click()
  await expect(page.getByText('Sale saved locally. Cloud sync is disabled in this demo.')).toBeVisible()
  await expect(page.getByText('Local queue (1) · sync disabled')).toBeVisible()
  await page.close()
  const reopened = await context.newPage()
  reopened.on('pageerror', error => errors.push(error.message))
  await reopened.goto('/')
  await expect(reopened.getByRole('heading', { name: '₱275.00' })).toBeVisible()
  await expect(reopened.getByText('Local queue (1) · sync disabled')).toBeVisible()
  await reopened.getByRole('button', { name: 'Stock', exact: true }).click()
  await expect(reopened.locator('article').filter({ hasText: 'Sinandomeng' }).getByText('95 kg')).toBeVisible()
  const overflow = await reopened.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(overflow).toBe(false)
  await reopened.screenshot({ path: `test-results/offline-stock-${test.info().project.name}.png`, fullPage: true })
  expect(errors).toEqual([])
})

test('offline refill, receiving, abono and cash close use local storage', async ({ page, context }) => {
  await page.goto('/')
  await offlineReady(page)
  await context.setOffline(true)
  await page.getByLabel('Business', { exact: true }).selectOption({ label: 'Water Refilling Station' })
  await page.getByRole('button', { name: 'Ops', exact: true }).click()
  await page.getByRole('button', { name: 'Cash close', exact: true }).click()
  await page.getByLabel('Opening cash').fill('1000')
  await page.getByRole('button', { name: 'Open cash session' }).click()
  await expect(page.getByText('Cash session opened.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Sale', exact: true }).click()
  await page.getByRole('combobox', { name: 'Item', exact: true }).selectOption({ label: 'Purified Water Refill — ₱30.00' })
  await page.getByLabel('Quantity').fill('3')
  await page.getByLabel('Paid via').selectOption({ label: 'Water Cash Drawer' })
  await page.getByRole('button', { name: 'Finalize sale' }).click()
  await expect(page.getByText('Sale saved locally.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Ops', exact: true }).click()
  await page.getByLabel('Quantity received').fill('1')
  await page.getByLabel('Total supplier cost').fill('140')
  await page.getByLabel('Paid from').selectOption({ label: 'Water Cash Drawer' })
  await page.getByRole('button', { name: 'Receive stock', exact: true }).last().click()
  await expect(page.getByText('Stock received.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Expense', exact: true }).click()
  await page.getByLabel('Amount (₱)', { exact: true }).fill('500')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Save expense' }).click()
  await expect(page.getByText('Expense saved as owner-funded abono;', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Cash close', exact: true }).click()
  await page.getByLabel('Actual cash counted').fill('940')
  await page.getByRole('button', { name: 'Close and reconcile', exact: true }).click()
  await expect(page.getByText('Cash session closed. Expected ₱950.00; variance -₱10.00.')).toBeVisible()
  await page.getByRole('button', { name: 'Stock', exact: true }).click()
  await expect(page.locator('article').filter({ hasText: 'New 5-Gallon Container' }).getByText('17 unit')).toBeVisible()
})
